version: "3.9"
services:
  placeholder-starter:
    image: postgres
    restart: always
    container_name: ai-chatbot
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
